# Missing values
```{r, include=FALSE}
# These will install required packages if they are not already installed
if (!require("ggplot2")) {
   install.packages("ggplot2")
   library(ggplot2)
}
if (!require("dplyr")) {
   install.packages("dplyr2")
   library(dplyr)
}
if (!require("knitr")) {
   install.packages("knitr")
   library(knitr)
}
if (!require("xtable")) {
   install.packages("xtable")
   library(xtable)
}
if (!require("caret")) {
   install.packages("caret")
   library(caret)
}
if (!require("reshape2")){
  install.packages("reshape2")
   library(reshape2)
} 
if (!require("gridExtra")){
  install.packages("gridExtra")
   library(gridExtra)
} 
if (!require("MASS")){
  install.packages("MASS")
   library(MASS)
} 
if (!require("reshape2")) {
   install.packages("nnet")
   library(lubridate)
}
if (!require("nnet")) {
   install.packages("reshape2")
   library(lubridate)
}
if (!require("tidyverse")) {
   install.packages("tidyverse")
   library(tidyverse)
}
if (!require("lubridate")) {
   install.packages("lubridate")
   library(lubridate)
}
if (!require("VIM")) {
   install.packages("VIM")
   library(lubridate)
}
if (!require("naniar")) {
   install.packages("naniar")
   library(lubridate)
}
if (!require("Amelia")) {
   install.packages("Amelia")
   library(lubridate)
}
if (!require("extracat")) {
   install.packages("extracat")
   library(lubridate)
}
knitr::opts_chunk$set(echo = TRUE)
```

Yaotian Dai
```{r}
admissions<-read.csv('C:/Users/pudon/Desktop/class/data visualization/final_project/MIMICIII_visualization/data/ADMISSIONS.csv')

patients<-read.csv("C:/Users/pudon/Desktop/class/data visualization/final_project/MIMICIII_visualization/data/PATIENTS.csv")

icu_stay <- read.csv("C:/Users/pudon/Desktop/class/data visualization/final_project/MIMICIII_visualization/data/ICUSTAYS.csv")

ICD<-read.csv("C:/Users/pudon/Desktop/class/data visualization/final_project/MIMICIII_visualization/data/DIAGNOSES_ICD.csv")
```

```{r}
admissions[admissions==""] <- NA
colSums(is.na(admissions))
missmap(admissions)
visna(admissions, sort="b")


```
```{r}
patients[patients==""] <- NA
colSums(is.na(patients))
missmap(patients)
visna(patients, sort="b")


```


```{r}
icu_stay[icu_stay==""] <- NA
colSums(is.na(icu_stay))
missmap(icu_stay)
visna(icu_stay, sort="b")
```

```{r}
ICD[ICD==""] <- NA
colSums(is.na(ICD))
missmap(ICD)



```


```{r}
comb[comb==""] <- NA
colSums(is.na(comb))
missmap(comb)
visna(comb, sort="b")

```