# Results
```{r, include=FALSE}
# These will install required packages if they are not already installed
if (!require("ggplot2")) {
   install.packages("ggplot2")
   library(ggplot2)
}
if (!require("dplyr")) {
   install.packages("dplyr2")
   library(dplyr)
}
if (!require("knitr")) {
   install.packages("knitr")
   library(knitr)
}
if (!require("xtable")) {
   install.packages("xtable")
   library(xtable)
}
if (!require("caret")) {
   install.packages("caret")
   library(caret)
}
if (!require("reshape2")){
  install.packages("reshape2")
   library(reshape2)
} 
if (!require("gridExtra")){
  install.packages("gridExtra")
   library(gridExtra)
} 
if (!require("MASS")){
  install.packages("MASS")
   library(MASS)
} 
if (!require("nnet")) {
   install.packages("nnet")
   library(nnet)
}
if (!require("tidyverse")) {
   install.packages("tidyverse")
   library(tidyverse)
}
if (!require("lubridate")) {
   install.packages("lubridate")
   library(lubridate)
}
if (!require("ggmosaic")) {
   install.packages("ggmosaic")
   library(ggmosaic)
}
knitr::opts_chunk$set(echo = TRUE)
```




Yaotian Dai
```{r}
#Some basic graphs
ggplot(comb,aes(x = GENDER))+geom_bar()+
  ggtitle("Amount of female patients and male patients accepted to ICU")
  
ggplot(comb, aes(x = AGE))+geom_bar()+
  ggtitle("Amount of patients of diffent age groups accepted to ICU")

ggplot(comb, aes(x = mortality_withinthirtydays))+geom_bar()+
  ggtitle("Amount of patients of die and alive within 30 days after accepted to ICU")

ggplot(comb, aes(x = ETHNICITY))+geom_bar()+
  ggtitle("Amount of patients of different Ethnicity accepted to ICU")

ggplot(comb, aes(x = INSURANCE))+geom_bar()+
  ggtitle("Amount of patients of different Insurance after accepted to ICU")

ggplot(comb, aes(x = ADMISSION_LOCATION))+geom_bar()+
  ggtitle("Amount of patients of different admission location before accepted to ICU")
```


Trying to find some patterns between mortality within 30 days and different factors
```{r}
h2 = comb$ETHNICITY
h1 = comb$mortality_withinthirtydays
df <- data_frame(h2,h1)%>%drop_na()
ggplot(comb,aes(h1,fill=h2))+geom_bar(position = "fill")+coord_flip()+ylab("Percentage")+xlab("die within 30 days")+theme(legend.position="right")+theme(legend.title = element_blank())+ggtitle("Percentage of patients divided by Ethnicity  ")+theme(plot.title = element_text(hjust = 0.5))
table2 <- table(comb$ETHNICITY)
prop.table(table2)


h2 = comb$GENDER
h1 = comb$mortality_withinthirtydays
df <- data_frame(h2,h1)%>%drop_na()
ggplot(comb,aes(h1,fill=h2))+geom_bar(position = "fill")+coord_flip()+ylab("Percentage")+xlab("die within 30 days")+theme(legend.position="right")+theme(legend.title = element_blank())+ggtitle("Percentage of patients die and alive within 30 days divided by Gender")+theme(plot.title = element_text(hjust = 0.5))

h2 = comb$INSURANCE
h1 = comb$mortality_withinthirtydays
df <- data_frame(h2,h1)%>%drop_na()
ggplot(comb,aes(h1,fill=h2))+geom_bar(position = "fill")+coord_flip()+ylab("Percentage")+xlab("die within 30 days")+theme(legend.position="right")+theme(legend.title = element_blank())+ggtitle("Percentage of patients die and alive within 30 days divided by Insurance type")+theme(plot.title = element_text(hjust = 0.5))

h2 = comb$DISEASE
h1 = comb$mortality_withinthirtydays
df <- data_frame(h2,h1)%>%drop_na()
ggplot(comb,aes(h1,fill=h2))+geom_bar(position = "fill")+coord_flip()+ylab("Percentage")+xlab("die within 30 days")+theme(legend.position="right")+theme(legend.title = element_blank())+ggtitle("Percentage of patients die and alive within 30 days divided by Disease type")+theme(plot.title = element_text(hjust = 0.5))

h2 = comb$ADMISSION_LOCATION
h1 = comb$mortality_withinthirtydays
df <- data_frame(h2,h1)%>%drop_na()
ggplot(comb,aes(h1,fill=h2))+geom_bar(position = "fill")+coord_flip()+ylab("Percentage")+xlab("die within 30 days")+theme(legend.position="right")+theme(legend.title = element_blank())+ggtitle("Percentage of patients die and alive within 30 days divided by differenct Admission Location")+theme(plot.title = element_text(hjust = 0.5))

```

```{r}
ggplot(data = comb)+
   geom_mosaic(aes(x = product(mortality_withinthirtydays,INSURANCE)), na.rm = TRUE)+
   labs(x = "Insurance type", y = "mortality_withinthirtydays")

ggplot(data = comb)+
   geom_mosaic(aes(x = product(mortality_withinthirtydays,ADMISSION_LOCATION)), na.rm = TRUE)+
   labs(x = "ADMISSION_LOCATION", y ="mortality_withinthirtydays" )

ggplot(data = comb)+
   geom_mosaic(aes(x = product(mortality_withinthirtydays,DISEASE)), na.rm = TRUE)+
   labs(x = "DISEASE", y = "mortality_withinthirtydays")


ggplot(data = comb)+
  geom_mosaic(aes(x = product(mortality_withinthirtydays, ADMISSION_LOCATION), fill= mortality_withinthirtydays), na.rm = TRUE)+
  labs(x = "ADMISSION_LOCATION", y = "mortality_withinthirtydays")+
  facet_grid(INSURANCE~.)

ggplot(data = comb)+
  geom_mosaic(aes(x = product(mortality_withinthirtydays, INSURANCE), fill= mortality_withinthirtydays), na.rm = TRUE)+
  labs(x = "Ethnicity", y = "mortality_withinthirtydays")+
  facet_grid(ADMISSION_LOCATION~.)

ggplot(data = comb)+
  geom_mosaic(aes(x = product(ADMISSION_LOCATION, INSURANCE), fill= ADMISSION_LOCATION), na.rm = TRUE)+
  labs(x = "Insurance Type", y ="Admission Location" )+
  facet_grid(mortality_withinthirtydays~.)


```