# interactive
<!DOCTYPE html>

<html>

<head>
<title>updating a bar chart with d3.js (v4)</title>
<script src="https://d3js.org/d3.v4.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<style>
.radio{
	text-align: center;
}
.row{
	text-align: center;
}
</style>

<body>

<div class='container'>
	<div class='row'>
	<h2> Age Distribution of Different Groups</h2>
					<div class='radio'>
						<label class='radio-inline'>
							<input type="radio" name="gender" value="g0" onclick='change(this.value)'> Group1
						</label>
						<label class='radio-inline'>
							<input type="radio" name="gender" value="g1" onclick='change(this.value)'> Group2
						</label>
						<label class='radio-inline'>
							<input type="radio" name="gender" value="both" onclick='change(this.value)' checked > both
						</label>
					</div>
			<svg class='chart'>
			</svg>
	</div>
</div>
</body>
<script>
//set up data

var bothData = [
  {
    "Group": "1",
    "viewer_age": "0-5",
    "count":"0"
  },
  {
    "Group": "0",
    "viewer_age": "0-5",
    "count":"7782"
  },
  {
   "Group": "1",
    "viewer_age": "5-10",
    "count":"0"
  },
  {
   "Group": "0",
    "viewer_age": "5-10",
    "count":"0"
  },
  {
    "Group": "1",
    "viewer_age": "10-15",
    "count":"1"
  },
  {
    "Group": "0",
    "viewer_age": "10-15",
    "count":"6"
  },
  {
   "Group": "1",
    "viewer_age": "15-20",
    "count":"147"
  },
   {
   "Group": "0",
    "viewer_age": "15-20",
    "count":"304"
  },
  {
   "Group": "1",
    "viewer_age": "20-25",
    "count":"373"
  },
  {
   "Group": "0",
    "viewer_age": "20-25",
    "count":"495"
  },
  {
   "Group": "1",
    "viewer_age": "25-30",
    "count":"322"
  },
   {
   "Group": "0",
    "viewer_age": "25-30",
    "count":"491"
  },
  {
   "Group": "1",
    "viewer_age": "30-35",
    "count":"374"
  },
  {
   "Group": "0",
    "viewer_age": "30-35",
    "count":"530"
  },
  {
   "Group": "1",
    "viewer_age": "35-40",
    "count":"465"
  },
  {
   "Group": "0",
    "viewer_age": "35-40",
    "count":"770"
  },
  {
   "Group": "1",
    "viewer_age": "40-45",
    "count":"663"
  },
  {
   "Group": "0",
    "viewer_age": "40-45",
    "count":"1113"
  },
  {
   "Group": "1",
    "viewer_age": "45-50",
    "count":"914"
  },
  {
   "Group": "0",
    "viewer_age": "45-50",
    "count":"1519"
  },
  {
   "Group": "1",
    "viewer_age": "50-55",
    "count":"1293"
  },
   {
   "Group": "0",
    "viewer_age": "50-55",
    "count":"1766"
  },
  {
   "Group": "1",
    "viewer_age": "55-60",
    "count":"1456"
  },
  {
   "Group": "0",
    "viewer_age": "55-60",
    "count":"2140"
  },
  {
   "Group": "1",
    "viewer_age": "60-65",
    "count":"1648"
  },
  {
   "Group": "0",
    "viewer_age": "60-65",
    "count":"2114"
  },
  {
   "Group": "1",
    "viewer_age": "65-70",
    "count":"1677"
  },
  {
   "Group": "0",
    "viewer_age": "65-70",
    "count":"2167"
  },
  {
   "Group": "1",
    "viewer_age": "70-75",
    "count":"1468"
  },
  {
   "Group": "0",
    "viewer_age": "70-75",
    "count":"2286"
  },
  {
   "Group": "1",
    "viewer_age": "75-80",
    "count":"1534"
  },
   {
   "Group": "0",
    "viewer_age": "75-80",
    "count":"2571"
  },
  {
   "Group": "1",
    "viewer_age": "80+",
    "count":"1648"
  },
  {
   "Group": "0",
    "viewer_age": "80+",
    "count":"4274"
  }];

var maleData = [];
var femaleData = [];

for(var i = 0; i < bothData.length; i++){
	if(bothData[i]["Group"] === "0"){
		maleData.push(bothData[i]);
	}else{
		femaleData.push(bothData[i]);
	}
}

//functions for toggling between data
function change(value){

	if(value === 'g0'){
		update(maleData);
	}else if(value === 'g1'){
		update(femaleData);
	}else{
		update(bothData);
	}
}

function update(data){
	//set domain for the x axis
	xChart.domain(data.map(function(d){ return d.viewer_age; }) );
	//set domain for y axis
	yChart.domain( [0, d3.max(data, function(d){ return +d.count; })] );
	
	//get the width of each bar 
	var barWidth = width / data.length;
	
	//select all bars on the graph, take them out, and exit the previous data set. 
	//then you can add/enter the new data set
	var bars = chart.selectAll(".bar")
					.remove()
					.exit()
					.data(data)		
	//now actually give each rectangle the corresponding data
	bars.enter()
		.append("rect")
		.attr("class", "bar")
		.attr("x", function(d, i){ return i * barWidth + 1 })
		.attr("y", function(d){ return yChart( d.count); })
		.attr("height", function(d){ return height - yChart(d.count); })
		.attr("width", barWidth - 1)
		.attr("fill", function(d){ 
			if(d.Group === "1"){
				return "rgb(251,180,174)";
			}else{
				return "rgb(179,205,227)";
			}
		});
	//left axis
	chart.select('.y')
		  .call(yAxis)
	//bottom axis
	chart.select('.xAxis')
		.attr("transform", "translate(0," + height + ")")
		.call(xAxis)
		.selectAll("text")
			.style("text-anchor", "end")
			.attr("dx", "-.8em")
			.attr("dy", ".15em")
			.attr("transform", function(d){
				return "rotate(-65)";
			});
			
}//end update

//set up chart
var margin = {top: 20, right: 20, bottom: 95, left: 50};
var width = 800;
var height = 500;

var chart = d3.select(".chart")
				.attr("width", width + margin.left + margin.right)
				.attr("height", height + margin.top + margin.bottom)
				.append("g")
				.attr("transform", "translate(" + margin.left + "," + margin.top + ")");

var xChart = d3.scaleBand()
				.range([0, width]);
				
var yChart = d3.scaleLinear()
				.range([height, 0]);

var xAxis = d3.axisBottom(xChart);
var yAxis = d3.axisLeft(yChart);

//set up axes
//left axis
	chart.append("g")
		  .attr("class", "y axis")
		  .call(yAxis)
		  
	//bottom axis
	chart.append("g")
		.attr("class", "xAxis")
		.attr("transform", "translate(0," + height + ")")
		.call(xAxis)
		.selectAll("text")
			.style("text-anchor", "end")
			.attr("dx", "-.8em")
			.attr("dy", ".15em")
			.attr("transform", function(d){
				return "rotate(-65)";
			});

//add labels
chart
	.append("text")
	.attr("transform", "translate(-35," +  (height+margin.bottom)/2 + ") rotate(-90)")
	.text("Count");
		
chart
	.append("text")
	.attr("transform", "translate(" + (width/2) + "," + (height + margin.bottom - 5) + ")")
	.text("Age Group");

//use bothData to begin with
update(bothData);
</script>

</html>
